server:
  port: 9099
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: identity
          uri: lb://IDENTITY
          predicates:
            - Path=/api/v1/identity-service/**


        - id: cart
          uri: lb://CART
          predicates:
            - Path=/api/v1/cart-service/**


        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/product-service/**


        - id: like-product
          uri: lb://LIKE-PRODUCT
          predicates:
            - Path=/api/v1/like-product-service/users/**


        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/order-service/**


        - id: review
          uri: lb://REVIEW
          predicates:
            - Path=/api/v1/review-service/**


        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/v1/notification-service/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
