server:
  port: 8086
spring:
  application:
    name: mail
  datasource:
    url: jdbc:mysql://localhost:3308/microservice
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  mail:
    host: smtp.gmail.com
    port: 587
    username: cristran040702@gmail.com
    password: wxjugsquhiyajgdc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 142564064113-lno4pp023aamu77gk7bljar2vt5cb83c.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - mail
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    topic: mail.exchange
  queue:
    register-account: register_account.queue
    forgot-pass: forgot_pass.queue
  routing-key:
    register-account: register_account.routing_key
    forgot-pass: forgot_pass.routing_key