server:
  port: 8081
spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3308/microservice
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true