server:
  port: 8085
spring:
  application:
    name: address
  datasource:
    url: jdbc:mysql://localhost:3308/microservice
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true