server:
  port: 8084
spring:
  application:
    name: review
  datasource:
    url: jdbc:mysql://localhost:3308/microservice
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true